### ISSUE TITLE
ClusterFlow format

### ISSUE THREAD

**Issue by papanito** [microsoft/fluentbit-containerd-cri-o-json-log#7]
# Bug Report

## Description

As I have not much experience in fluentd, I struggle a bit to translate your docu into a working `ClusterFlow` config. I figured starting with something like thi

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: all-logs
  namespace: cattle-logging-system
  filters:
    - parser:
        key_name: log
        parse:
          expression: >-
            ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*)
            (?<log>.*)$
          time_format: '%Y-%m-%dT%H:%M:%S.%L%z'
  globalOutputRefs:
    - cluster-output-splunk
```

But don't know where to go from there... 

## Expected Behavior

N/A

## Reproduce

N/A

## Additional Context

N/A
